domain: ""
modules:
  crtsh: true
  subfinder: true
  permutations: true
  revwhois: true
  amass: true
  dns_resolution: true
  http_check: false

permutations:
  wordlist: "data/perms.txt"
  max_depth: 2
